### ISSUE TITLE
current master does not compile

### ISSUE THREAD

**Issue by tacker66** [bracci/Qlockthree#7]
trying to compile a07bde33 "Optimized transition timing" gives

Qlockthree.ino:206:22: fatal error: TimerOne.h: No such file or directory

Thomas

**Comment by bracci** [comment]
Hi Thomas, thanks for your change requests. I applied them. TimerOne is a Library you can get and install via Arduino Library Manager. Debug mode is almost unusable due to storage limit on this small uC. But you can use (uncomment) debug modes in specific files you need it. Best regards, Manuel
